// Sample karate roster data from CSV export
import { Athlete } from './bracketGenerator';

export const SAMPLE_ROSTER: Athlete[] = [
  {
    registrationNo: 'REG-2026-001',
    fullName: 'Ahmad Daniel',
    gender: 'Male',
    weight: 64.5,
    height: 172,
    club: 'Senshi Karate Academy',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-002',
    fullName: 'Chloe Tan',
    gender: 'Female',
    weight: 52,
    height: 161,
    club: 'Goju-Ryu Karate Club',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-003',
    fullName: 'Subramaniam Krishnan',
    gender: 'Male',
    weight: 78.2,
    height: 178,
    club: 'Senshi Karate Academy',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-004',
    fullName: 'Muhammad Ryan',
    gender: 'Male',
    weight: 58.5,
    height: 168,
    club: 'Tiger Claw Dojo',
    status: 'Confirmed',
    medicalClearance: 'Review Needed',
  },
  {
    registrationNo: 'REG-2026-005',
    fullName: 'Kenji Sato',
    gender: 'Male',
    weight: 72,
    height: 175,
    club: 'Kyokushin Jakarta',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-006',
    fullName: 'Anisha Putri',
    gender: 'Female',
    weight: 48.5,
    height: 158,
    club: 'Kyokushin Jakarta',
    status: 'Confirmed',
    medicalClearance: 'Action Required',
  },
  {
    registrationNo: 'REG-2026-007',
    fullName: 'Ethan Lim',
    gender: 'Male',
    weight: 66.8,
    height: 170,
    club: 'Budokan Singapore',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-008',
    fullName: 'Somporn Yodrak',
    gender: 'Male',
    weight: 84,
    height: 182,
    club: 'Tiger Claw Dojo',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-009',
    fullName: 'Hazwan Faris',
    gender: 'Male',
    weight: 58,
    height: 167,
    club: 'Senshi Karate Academy',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-010',
    fullName: 'Remy Azlan',
    gender: 'Male',
    weight: 59.5,
    height: 165,
    club: 'Goju-Ryu Karate Club',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-011',
    fullName: 'Tan Wei Jie',
    gender: 'Male',
    weight: 57.5,
    height: 163,
    club: 'Goju-Ryu Karate Club',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-012',
    fullName: 'Wan Ariff',
    gender: 'Male',
    weight: 60,
    height: 169,
    club: 'Tiger Claw Dojo',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-013',
    fullName: 'Syafiq Hakim',
    gender: 'Male',
    weight: 65,
    height: 172,
    club: 'Senshi Karate Academy',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-014',
    fullName: 'Bryan Ng',
    gender: 'Male',
    weight: 63,
    height: 170,
    club: 'Budokan Singapore',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-015',
    fullName: 'Nguyen Minh Duc',
    gender: 'Male',
    weight: 66.5,
    height: 174,
    club: 'Kyokushin Jakarta',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-016',
    fullName: 'Faiz Irfan',
    gender: 'Male',
    weight: 62,
    height: 168,
    club: 'Senshi Karate Academy',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-017',
    fullName: 'Amirul Hafiz',
    gender: 'Male',
    weight: 73,
    height: 176,
    club: 'Goju-Ryu Karate Club',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-018',
    fullName: 'Wanchai Burakorn',
    gender: 'Male',
    weight: 74.5,
    height: 177,
    club: 'Tiger Claw Dojo',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-019',
    fullName: 'Ruzaini Musa',
    gender: 'Male',
    weight: 70.5,
    height: 173,
    club: 'Senshi Karate Academy',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-020',
    fullName: 'Dani Prasetyo',
    gender: 'Male',
    weight: 68,
    height: 171,
    club: 'Kyokushin Jakarta',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-021',
    fullName: 'Norzaidi Hamdan',
    gender: 'Male',
    weight: 80,
    height: 183,
    club: 'Senshi Karate Academy',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-022',
    fullName: 'Takeshi Yamamoto',
    gender: 'Male',
    weight: 82.5,
    height: 184,
    club: 'Budokan Singapore',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-023',
    fullName: 'Khairul Anwar',
    gender: 'Male',
    weight: 76.5,
    height: 179,
    club: 'Tiger Claw Dojo',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-024',
    fullName: 'Fernando Santos',
    gender: 'Male',
    weight: 79,
    height: 180,
    club: 'Kyokushin Jakarta',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-025',
    fullName: 'Nurul Ain Siti',
    gender: 'Female',
    weight: 48,
    height: 155,
    club: 'Senshi Karate Academy',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-026',
    fullName: 'Priya Nambiar',
    gender: 'Female',
    weight: 49.5,
    height: 157,
    club: 'Goju-Ryu Karate Club',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-027',
    fullName: 'Mei Lin Chan',
    gender: 'Female',
    weight: 47,
    height: 153,
    club: 'Goju-Ryu Karate Club',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-028',
    fullName: 'Nattaya Kaewkla',
    gender: 'Female',
    weight: 50,
    height: 160,
    club: 'Tiger Claw Dojo',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-029',
    fullName: 'Aisyah Zainudin',
    gender: 'Female',
    weight: 53,
    height: 162,
    club: 'Senshi Karate Academy',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-030',
    fullName: 'Lisa Nguyen',
    gender: 'Female',
    weight: 54.5,
    height: 163,
    club: 'Kyokushin Jakarta',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-031',
    fullName: 'Siti Hajar',
    gender: 'Female',
    weight: 51.5,
    height: 160,
    club: 'Tiger Claw Dojo',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-032',
    fullName: 'Grace Seah',
    gender: 'Female',
    weight: 52.5,
    height: 161,
    club: 'Budokan Singapore',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-033',
    fullName: 'Roszaida Othman',
    gender: 'Female',
    weight: 58,
    height: 165,
    club: 'Senshi Karate Academy',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-034',
    fullName: 'Hana Kobayashi',
    gender: 'Female',
    weight: 60.5,
    height: 167,
    club: 'Budokan Singapore',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-035',
    fullName: 'Natasha Yip',
    gender: 'Female',
    weight: 56.5,
    height: 166,
    club: 'Goju-Ryu Karate Club',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-036',
    fullName: 'Sofia Cruz',
    gender: 'Female',
    weight: 57.5,
    height: 164,
    club: 'Kyokushin Jakarta',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-037',
    fullName: 'Zulfahmi Arif',
    gender: 'Male',
    weight: 68,
    height: 173,
    club: 'Senshi Karate Academy',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-038',
    fullName: 'Hideki Tanaka',
    gender: 'Male',
    weight: 72,
    height: 176,
    club: 'Budokan Singapore',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-039',
    fullName: 'Luqmanul Hakim',
    gender: 'Male',
    weight: 65,
    height: 170,
    club: 'Goju-Ryu Karate Club',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-040',
    fullName: 'Panya Suthirak',
    gender: 'Male',
    weight: 70,
    height: 172,
    club: 'Tiger Claw Dojo',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-041',
    fullName: 'Zara Hidayah',
    gender: 'Female',
    weight: 55,
    height: 162,
    club: 'Senshi Karate Academy',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-042',
    fullName: 'Yui Watanabe',
    gender: 'Female',
    weight: 52,
    height: 159,
    club: 'Budokan Singapore',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-043',
    fullName: 'Indah Permata',
    gender: 'Female',
    weight: 48,
    height: 156,
    club: 'Kyokushin Jakarta',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-044',
    fullName: 'Amira Farida',
    gender: 'Female',
    weight: 58,
    height: 163,
    club: 'Tiger Claw Dojo',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-045',
    fullName: 'Hafiz Amsyar',
    gender: 'Male',
    weight: 53,
    height: 163,
    club: 'Senshi Karate Academy',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-046',
    fullName: 'Kevin Chong',
    gender: 'Male',
    weight: 54,
    height: 164,
    club: 'Goju-Ryu Karate Club',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-047',
    fullName: 'Syamil Aqil',
    gender: 'Male',
    weight: 52,
    height: 161,
    club: 'Tiger Claw Dojo',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-048',
    fullName: 'Danial Akmal',
    gender: 'Male',
    weight: 55,
    height: 165,
    club: 'Senshi Karate Academy',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-049',
    fullName: 'Rizwan Hakimi',
    gender: 'Male',
    weight: 59,
    height: 166,
    club: 'Goju-Ryu Karate Club',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-050',
    fullName: 'Darren Khor',
    gender: 'Male',
    weight: 60.5,
    height: 167,
    club: 'Goju-Ryu Karate Club',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-051',
    fullName: 'Aiman Zulkifli',
    gender: 'Male',
    weight: 57.5,
    height: 165,
    club: 'Senshi Karate Academy',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-052',
    fullName: 'Isyraf Izzat',
    gender: 'Male',
    weight: 58.5,
    height: 164,
    club: 'Tiger Claw Dojo',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-053',
    fullName: 'Anis Husna',
    gender: 'Female',
    weight: 46,
    height: 155,
    club: 'Senshi Karate Academy',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-054',
    fullName: 'Yee Xin Rong',
    gender: 'Female',
    weight: 47,
    height: 156,
    club: 'Goju-Ryu Karate Club',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-055',
    fullName: 'Batrisyia Nadhira',
    gender: 'Female',
    weight: 45,
    height: 153,
    club: 'Tiger Claw Dojo',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
  {
    registrationNo: 'REG-2026-056',
    fullName: 'Suri Aina',
    gender: 'Female',
    weight: 48,
    height: 157,
    club: 'Senshi Karate Academy',
    status: 'Confirmed',
    medicalClearance: 'Cleared',
  },
];
